name: OnlyEnchant
version: 1.0
main: ru.onlydev.enchant.Main
authors: [ OnlyDev ]
description: Плагин, добавляющий возможность зачаровывать вещи, перенося книгу с зачарованием на предмет прямо в инвентаре
website: kwork.ru/user/mishalikelego
